# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 922)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Application-icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"\n"
"/* -----------------------------------------------------------\n"
"   MAIN WINDOW COLORS\n"
"----------------------------------------------------------- */\n"
"QMainWindow {\n"
"    background: #1a1a1d;       /* ASURT dark gray */\n"
"    color: #e8eefc;\n"
"}\n"
"\n"
"/* -----------------------------------------------------------\n"
"   GROUPBOXES\n"
"----------------------------------------------------------- */\n"
"QGroupBox {\n"
"    border: 1px solid #2b2b2d;\n"
"    border-radius: 12px;\n"
"    margin-top: 24px;\n"
"    padding: 12px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 14px;\n"
"    top: 6px;\n"
"    color: #bfbfc8;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* -----------------------------------------------------------\n"
"   TABS\n"
"----------------------------------------------------------- */\n"
"QTabWidget::pane {\n"
"    border: 0;\n"
"    top: -1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #101013;\n"
"    color: #bfbfc8;\n"
"    padding: 8px 16px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    margin-right: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #2a0f12;      /* Dark red tone */\n"
"    color: #ffffff;\n"
"    border-bottom: 2px solid #d90429;\n"
"}\n"
"\n"
"/* -----------------------------------------------------------\n"
"   LABEL STYLING\n"
"----------------------------------------------------------- */\n"
"QLabel {\n"
"    color: #e8eefc;\n"
"}\n"
"\n"
"QLabel#titleLabel, QLabel#teamNameLabel {\n"
"    font-size: 80px;\n"
"    font-weight: 900;\n"
"    letter-spacing: 1.2px;\n"
"    color: #d6d6d6;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* -----------------------------------------------------------\n"
"   COMBOBOX, SPINBOX, LINEEDIT\n"
"----------------------------------------------------------- */\n"
"QComboBox, QSpinBox, QLineEdit {\n"
"    background: #101013;\n"
"    border: 1px solid #2b2b2d;\n"
"    border-radius: 8px;\n"
"    color: #e8eefc;\n"
"    padding: 4px 8px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"QComboBox:hover, QSpinBox:hover, QLineEdit:hover {\n"
"    border: 1px solid #d90429;\n"
"}\n"
"\n"
"/* ================================\n"
"   COMBOBOX TEXT (CLOSED STATE)\n"
"================================ */\n"
"QComboBox#cmbSession {\n"
"    min-height: 42px;        /* make it taller */\n"
"    padding-left: 10px;\n"
"    padding-right: 28px;     /* space for arrow */\n"
"}\n"
"\n"
"/* 🔥 THIS controls the visible text */\n"
"QComboBox#cmbSession QLineEdit {\n"
"    font-size: 20px;         /* BIG TEXT */\n"
"    font-weight: 500;\n"
"    color: #e8eefc;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ================================\n"
"   COMBOBOX DROPDOWN\n"
"================================ */\n"
"QComboBox#cmbSession QAbstractItemView {\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"    background: #101013;\n"
"    color: #e8eefc;\n"
"    selection-background-color: #2a0f12;\n"
"}\n"
"\n"
"/* Arrow stays clean */\n"
"QComboBox#cmbSession::down-arrow {\n"
"    image: none;\n"
"    border: 4px solid #e8eefc;\n"
"    border-top-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-right-color: transparent;\n"
"}\n"
"\n"
"\n"
"\n"
"/* -----------------------------------------------------------\n"
"   PROGRESS BARS (Battery, Thermal, Electrical)\n"
"----------------------------------------------------------- */\n"
"QProgressBar {\n"
"    border: 1px solid #2b2b2d;\n"
"    border-radius: 8px;\n"
"    text-align: center;\n"
"    height: 20px;\n"
"    background: #101013;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #d90429;      /* Main ASURT red */\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* -----------------------------------------------------------\n"
"   DARKER RED VARIANTS FOR THERMAL RANGES\n"
"----------------------------------------------------------- */\n"
"QProgressBar[thermal=\"true\"]::chunk {\n"
"    background-color: #8b0000;\n"
"}\n"
"\n"
"QProgressBar[electrical=\"true\"]::chunk {\n"
"    background-color: #d90429;\n"
"}\n"
"\n"
"/* -----------------------------------------------------------\n"
"   GENERAL FRAMES\n"
"----------------------------------------------------------- */\n"
"QFrame {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Divider frame */\n"
"QFrame#thinDivider {\n"
"    background: #2b2b2d;\n"
"}\n"
"\n"
"/* -----------------------------------------------------------\n"
"   QGRAPHICSVIEW (Track Map)\n"
"----------------------------------------------------------- */\n"
"QGraphicsView#trackMapView {\n"
"    background: #0d1222;\n"
"    border: 1px solid #2b3142;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"\n"
"/* -----------------------------------------------------------\n"
"   BUTTONS (if added later)\n"
"----------------------------------------------------------- */\n"
"QPushButton {\n"
"    background: #111114;\n"
"    border: 1px solid #2b2b2d;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #2a0f12;\n"
"    border: 1px solid #d90429;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #d90429;\n"
"}\n"
"\n"
"/* -----------------------------------------------------------\n"
"   MEASUREMENT VALUES — Improved Readability (+2pt, clearer)\n"
"----------------------------------------------------------- */\n"
"\n"
"/* Main measurement values — speed, voltage, temperature, GPS, battery %, etc. */\n"
"/* ===========================================================\n"
"   BASE MEASUREMENT LABELS (NON-THERMAL)\n"
"=========================================================== */\n"
"QLabel.measure {\n"
"    font-size: 24px;\n"
"    font-weight: 700;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* ===========================================================\n"
"   THERMAL TAB — BASE VALUES\n"
"=========================================================== */\n"
"\n"
"/* Sub descriptions remain softer */\n"
"QLabel[data-type=\"subtext\"] {\n"
"    font-size: 13px;\n"
"    color: #9aa5b8;\n"
"}\n"
"\n"
"/* Unit labels (°C, km/h, V, A, W, etc.) */\n"
"QLabel[data-type=\"unit\"] {\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    color: #d7d7e0;\n"
"}\n"
"\n"
"QSpinBox#spinLap {\n"
"    background: #101013;\n"
"    border: 1px solid #2b2b2d;\n"
"    border-radius: 8px;\n"
"    color: #e8eefc;\n"
"    padding: 4px 8px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"/* 🔥 THIS is what controls the number */\n"
"QSpinBox::up-button,\n"
"QSpinBox::down-button {\n"
"    width: 18px;\n"
"}\n"
"\n"
"QSpinBox#spinLap QLineEdit {\n"
"    font-size: 20px;\n"
"    color: #e8eefc;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ===========================================================\n"
"   THERMAL TAB — SCOPED STYLING ONLY\n"
"=========================================================== */\n"
"\n"
"QWidget#tabThermal {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QWidget#tabThermal QGroupBox {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #151922, stop:1 #0f1218);\n"
"    border: 1px solid #2a3140;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QWidget#tabThermal QGroupBox::title {\n"
"    color: #7fb3ff;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 0.6px;\n"
"}\n"
"\n"
"QLabel.measure {\n"
"    font-size: 22px;\n"
"    font-weight: 700;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QWidget#tabThermal QLabel.measure {\n"
"    font-size: 26px;\n"
"    font-weight: 800;\n"
"    color: #eaf1ff;\n"
"}\n"
"\n"
"QWidget#tabThermal QLabel.summaryText {\n"
"    font-size: 26px;\n"
"    font-weight: 600;\n"
"    color: #a8b3cf;\n"
"}\n"
"\n"
"QWidget#tabThermal QLabel.summaryValue {\n"
"    font-size: 36px;\n"
"    font-weight: 900;\n"
"    color: #5fd1ff;\n"
"}\n"
"/* ===========================================================\n"
"   ELECTRICAL TAB\n"
"=========================================================== */\n"
"\n"
"QWidget#tabElectrical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QWidget#tabElectrical QGroupBox#grpElectricalOverview {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #151922,\n"
"        stop:1 #0f1218\n"
"    );\n"
"    border: 1px solid #2a3140;\n"
"    border-radius: 16px;\n"
"    padding: 24px;\n"
"}\n"
"\n"
"\n"
"QGroupBox.elecCard {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #151922,\n"
"        stop:1 #0f1218\n"
"    );\n"
"    border: 1px solid #2a3140;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QGroupBox.elecCard::title {\n"
"    color: #7fb3ff;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 0.6px;\n"
"}\n"
"\n"
"QWidget#tabElectrical QGroupBox::title {\n"
"    color: #7fb3ff;\n"
"    font-size: 18px;\n"
"    font-weight: 800;\n"
"    letter-spacing: 1px;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"\n"
"/* Left text */\n"
"QWidget#tabElectrical QLabel.electricalLabel {\n"
"    font-size: 22px;\n"
"    font-weight: 600;\n"
"    color: #a8b3cf;\n"
"}\n"
"\n"
"\n"
"/* Right values */\n"
"QWidget#tabElectrical QLabel.electricalValue {\n"
"    font-size: 36px;          /* BIG */\n"
"    font-weight: 900;\n"
"    color: #5fd1ff;\n"
"}\n"
"\n"
"\n"
"/* ===========================================================\n"
"   ELECTRICAL TAB — SOC PROGRESS BAR (THICK + LARGE TEXT)\n"
"=========================================================== */\n"
"\n"
"QWidget#tabElectrical QProgressBar#progressElecSOC {\n"
"    min-height: 36px;            /* FORCE thickness */\n"
"    max-height: 36px;\n"
"    border-radius: 18px;\n"
"\n"
"    border: 1px solid #2b3142;\n"
"    background: #101013;\n"
"\n"
"    color: white;\n"
"    font-size: 20px;             /* BIG text inside bar */\n"
"    font-weight: 800;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QWidget#tabElectrical QProgressBar#progressElecSOC::chunk {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #d90429,\n"
"        stop:1 #ff4d6d\n"
"    );\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"\n"
"/* ===========================================================\n"
"   ELECTRICAL TAB — LARGE DASHBOARD STYLING\n"
"=========================================================== */\n"
"\n"
"QWidget#tabElectrical QLabel.electricalLabel {\n"
"    font-size: 35px;\n"
"    font-weight: 1000;\n"
"    color: #a8b3cf;\n"
"}\n"
"\n"
"QWidget#tabElectrical QLabel.elecValue {\n"
"    font-size: 32px;          /* BIG numbers */\n"
"    font-weight: 900;\n"
"    color: #5fd1ff;\n"
"}\n"
"\n"
"/* Spacing between rows */\n"
"QWidget#tabElectrical QGridLayout {\n"
"    row-gap: 18px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_central = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_central.setObjectName("verticalLayout_central")
        self.hdr = QtWidgets.QWidget(self.centralwidget)
        self.hdr.setObjectName("hdr")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout(self.hdr)
        self.horizontalLayout_header.setContentsMargins(12, -1, 12, -1)
        self.horizontalLayout_header.setSpacing(10)
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        self.teamLogo = QtWidgets.QLabel(self.hdr)
        self.teamLogo.setMinimumSize(QtCore.QSize(220, 60))
        self.teamLogo.setPixmap(QtGui.QPixmap("../assets/New Racing Team Logo.png"))
        self.teamLogo.setScaledContents(True)
        self.teamLogo.setObjectName("teamLogo")
        self.horizontalLayout_header.addWidget(self.teamLogo)
        self.titleLabel = QtWidgets.QLabel(self.hdr)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_header.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem)
        self.hostedByLabel = QtWidgets.QLabel(self.hdr)
        self.hostedByLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.hostedByLabel.setObjectName("hostedByLabel")
        self.horizontalLayout_header.addWidget(self.hostedByLabel)
        self.hostedByLogo = QtWidgets.QLabel(self.hdr)
        self.hostedByLogo.setMinimumSize(QtCore.QSize(40, 40))
        self.hostedByLogo.setPixmap(QtGui.QPixmap("../assets/Shell.png"))
        self.hostedByLogo.setScaledContents(True)
        self.hostedByLogo.setObjectName("hostedByLogo")
        self.horizontalLayout_header.addWidget(self.hostedByLogo)
        self.verticalLayout_central.addWidget(self.hdr)
        self.topInfo = QtWidgets.QWidget(self.centralwidget)
        self.topInfo.setObjectName("topInfo")
        self.horizontalLayout_top = QtWidgets.QHBoxLayout(self.topInfo)
        self.horizontalLayout_top.setContentsMargins(12, -1, 12, -1)
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.grpSession = QtWidgets.QGroupBox(self.topInfo)
        self.grpSession.setObjectName("grpSession")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.grpSession)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.cmbSession = QtWidgets.QComboBox(self.grpSession)
        self.cmbSession.setObjectName("cmbSession")
        self.cmbSession.addItem("")
        self.cmbSession.addItem("")
        self.cmbSession.addItem("")
        self.verticalLayout_28.addWidget(self.cmbSession)
        self.horizontalLayout_top.addWidget(self.grpSession)
        self.grpLap = QtWidgets.QGroupBox(self.topInfo)
        self.grpLap.setObjectName("grpLap")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.grpLap)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.spinLap = QtWidgets.QSpinBox(self.grpLap)
        self.spinLap.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinLap.setMinimum(0)
        self.spinLap.setMaximum(999)
        self.spinLap.setProperty("value", 1)
        self.spinLap.setObjectName("spinLap")
        self.verticalLayout_29.addWidget(self.spinLap)
        self.horizontalLayout_top.addWidget(self.grpLap)
        self.grpSpeedTop = QtWidgets.QGroupBox(self.topInfo)
        self.grpSpeedTop.setObjectName("grpSpeedTop")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.grpSpeedTop)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.lblSpeedTop = QtWidgets.QLabel(self.grpSpeedTop)
        self.lblSpeedTop.setStyleSheet("QLabel{}")
        self.lblSpeedTop.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSpeedTop.setObjectName("lblSpeedTop")
        self.verticalLayout_30.addWidget(self.lblSpeedTop)
        self.horizontalLayout_top.addWidget(self.grpSpeedTop)
        self.grpBattery = QtWidgets.QGroupBox(self.topInfo)
        self.grpBattery.setObjectName("grpBattery")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.grpBattery)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.progressBattery = QtWidgets.QProgressBar(self.grpBattery)
        self.progressBattery.setProperty("value", 10)
        self.progressBattery.setObjectName("progressBattery")
        self.verticalLayout_31.addWidget(self.progressBattery)
        self.horizontalLayout_top.addWidget(self.grpBattery)
        self.grpTimeTop = QtWidgets.QGroupBox(self.topInfo)
        self.grpTimeTop.setObjectName("grpTimeTop")
        self.verticalLayout_timeTop = QtWidgets.QVBoxLayout(self.grpTimeTop)
        self.verticalLayout_timeTop.setObjectName("verticalLayout_timeTop")
        self.lblTimeTop = QtWidgets.QLabel(self.grpTimeTop)
        self.lblTimeTop.setStyleSheet("QLabel{}")
        self.lblTimeTop.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimeTop.setObjectName("lblTimeTop")
        self.verticalLayout_timeTop.addWidget(self.lblTimeTop)
        self.horizontalLayout_top.addWidget(self.grpTimeTop)
        self.grpAmbientTop = QtWidgets.QGroupBox(self.topInfo)
        self.grpAmbientTop.setObjectName("grpAmbientTop")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.grpAmbientTop)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.lblAmbientTop = QtWidgets.QLabel(self.grpAmbientTop)
        self.lblAmbientTop.setStyleSheet("QLabel{}")
        self.lblAmbientTop.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAmbientTop.setObjectName("lblAmbientTop")
        self.verticalLayout_32.addWidget(self.lblAmbientTop)
        self.horizontalLayout_top.addWidget(self.grpAmbientTop)
        self.verticalLayout_central.addWidget(self.topInfo)
        self.tabsMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabsMain.setObjectName("tabsMain")
        self.tabOverview = QtWidgets.QWidget()
        self.tabOverview.setObjectName("tabOverview")
        self.verticalLayout_overview = QtWidgets.QVBoxLayout(self.tabOverview)
        self.verticalLayout_overview.setContentsMargins(12, -1, 12, -1)
        self.verticalLayout_overview.setObjectName("verticalLayout_overview")
        self.horizontalLayout_over1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_over1.setObjectName("horizontalLayout_over1")
        self.grpVehicleSpeed = QtWidgets.QGroupBox(self.tabOverview)
        self.grpVehicleSpeed.setObjectName("grpVehicleSpeed")
        self.verticalLayout_vehspd = QtWidgets.QVBoxLayout(self.grpVehicleSpeed)
        self.verticalLayout_vehspd.setObjectName("verticalLayout_vehspd")
        self.frameGauge = QtWidgets.QFrame(self.grpVehicleSpeed)
        self.frameGauge.setMinimumSize(QtCore.QSize(400, 260))
        self.frameGauge.setStyleSheet("background: transparent;")
        self.frameGauge.setObjectName("frameGauge")
        self.stackedGauge = QtWidgets.QGridLayout(self.frameGauge)
        self.stackedGauge.setObjectName("stackedGauge")
        self.lblGaugeBg = QtWidgets.QLabel(self.frameGauge)
        self.lblGaugeBg.setPixmap(QtGui.QPixmap("../assets/new_gauge.png"))
        self.lblGaugeBg.setScaledContents(True)
        self.lblGaugeBg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGaugeBg.setObjectName("lblGaugeBg")
        self.stackedGauge.addWidget(self.lblGaugeBg, 0, 0, 1, 1)
        self.lblGaugeNeedle = QtWidgets.QLabel(self.frameGauge)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lblGaugeNeedle.sizePolicy().hasHeightForWidth())
        self.lblGaugeNeedle.setSizePolicy(sizePolicy)
        self.lblGaugeNeedle.setPixmap(QtGui.QPixmap("../assets/new_needle.png"))
        self.lblGaugeNeedle.setScaledContents(True)
        self.lblGaugeNeedle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGaugeNeedle.setObjectName("lblGaugeNeedle")
        self.stackedGauge.addWidget(self.lblGaugeNeedle, 0, 0, 1, 1)
        self.verticalLayout_vehspd.addWidget(self.frameGauge)
        self.horizontalLayout_speedval = QtWidgets.QHBoxLayout()
        self.horizontalLayout_speedval.setObjectName("horizontalLayout_speedval")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_speedval.addItem(spacerItem1)
        self.lblSpeedValue = QtWidgets.QLabel(self.grpVehicleSpeed)
        self.lblSpeedValue.setStyleSheet("QLabel{}")
        self.lblSpeedValue.setObjectName("lblSpeedValue")
        self.horizontalLayout_speedval.addWidget(self.lblSpeedValue)
        self.lblSpeedUnits = QtWidgets.QLabel(self.grpVehicleSpeed)
        self.lblSpeedUnits.setStyleSheet("QLabel{}")
        self.lblSpeedUnits.setObjectName("lblSpeedUnits")
        self.horizontalLayout_speedval.addWidget(self.lblSpeedUnits)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_speedval.addItem(spacerItem2)
        self.verticalLayout_vehspd.addLayout(self.horizontalLayout_speedval)
        self.horizontalLayout_over1.addWidget(self.grpVehicleSpeed)
        self.grpTrackMap = QtWidgets.QGroupBox(self.tabOverview)
        self.grpTrackMap.setObjectName("grpTrackMap")
        self.verticalLayout_track = QtWidgets.QVBoxLayout(self.grpTrackMap)
        self.verticalLayout_track.setObjectName("verticalLayout_track")
        self.trackMapView = QtWidgets.QGraphicsView(self.grpTrackMap)
        self.trackMapView.setMinimumSize(QtCore.QSize(520, 240))
        self.trackMapView.setStyleSheet("QGraphicsView{background:#101629;border:1px solid #2b3142;border-radius:8px;}")
        self.trackMapView.setObjectName("trackMapView")
        self.verticalLayout_track.addWidget(self.trackMapView)
        self.grid_latlon = QtWidgets.QGridLayout()
        self.grid_latlon.setObjectName("grid_latlon")
        self.labelGPS = QtWidgets.QLabel(self.grpTrackMap)
        self.labelGPS.setObjectName("labelGPS")
        self.grid_latlon.addWidget(self.labelGPS, 0, 0, 1, 1)
        self.lblLat = QtWidgets.QLabel(self.grpTrackMap)
        self.lblLat.setObjectName("lblLat")
        self.grid_latlon.addWidget(self.lblLat, 0, 1, 1, 1)
        self.labelHeading = QtWidgets.QLabel(self.grpTrackMap)
        self.labelHeading.setObjectName("labelHeading")
        self.grid_latlon.addWidget(self.labelHeading, 0, 2, 1, 1)
        self.lblHeading = QtWidgets.QLabel(self.grpTrackMap)
        self.lblHeading.setObjectName("lblHeading")
        self.grid_latlon.addWidget(self.lblHeading, 0, 3, 1, 1)
        self.lblHeadingDir = QtWidgets.QLabel(self.grpTrackMap)
        self.lblHeadingDir.setObjectName("lblHeadingDir")
        self.grid_latlon.addWidget(self.lblHeadingDir, 0, 4, 1, 1)
        self.verticalLayout_track.addLayout(self.grid_latlon)
        self.horizontalLayout_over1.addWidget(self.grpTrackMap)
        self.horizontalLayout_over1.setStretch(0, 1)
        self.horizontalLayout_over1.setStretch(1, 1)
        self.verticalLayout_overview.addLayout(self.horizontalLayout_over1)
        self.horizontalLayout_over2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_over2.setObjectName("horizontalLayout_over2")
        self.grpPackVoltage = QtWidgets.QGroupBox(self.tabOverview)
        self.grpPackVoltage.setObjectName("grpPackVoltage")
        self.verticalLayout_pv = QtWidgets.QVBoxLayout(self.grpPackVoltage)
        self.verticalLayout_pv.setObjectName("verticalLayout_pv")
        self.lblPackVoltage = QtWidgets.QLabel(self.grpPackVoltage)
        self.lblPackVoltage.setStyleSheet("QLabel{}")
        self.lblPackVoltage.setObjectName("lblPackVoltage")
        self.verticalLayout_pv.addWidget(self.lblPackVoltage)
        self.lblPackVoltageSub = QtWidgets.QLabel(self.grpPackVoltage)
        self.lblPackVoltageSub.setStyleSheet("QLabel{color:#8ea2c8;}")
        self.lblPackVoltageSub.setObjectName("lblPackVoltageSub")
        self.verticalLayout_pv.addWidget(self.lblPackVoltageSub)
        self.horizontalLayout_over2.addWidget(self.grpPackVoltage)
        self.grpInvTemp = QtWidgets.QGroupBox(self.tabOverview)
        self.grpInvTemp.setObjectName("grpInvTemp")
        self.verticalLayout_it = QtWidgets.QVBoxLayout(self.grpInvTemp)
        self.verticalLayout_it.setObjectName("verticalLayout_it")
        self.lblInverterTemp = QtWidgets.QLabel(self.grpInvTemp)
        self.lblInverterTemp.setStyleSheet("QLabel{}")
        self.lblInverterTemp.setObjectName("lblInverterTemp")
        self.verticalLayout_it.addWidget(self.lblInverterTemp)
        self.lblInvTempSub = QtWidgets.QLabel(self.grpInvTemp)
        self.lblInvTempSub.setStyleSheet("QLabel{color:#8ea2c8;}")
        self.lblInvTempSub.setObjectName("lblInvTempSub")
        self.verticalLayout_it.addWidget(self.lblInvTempSub)
        self.horizontalLayout_over2.addWidget(self.grpInvTemp)
        self.grpLeftWheelSpeed = QtWidgets.QGroupBox(self.tabOverview)
        self.grpLeftWheelSpeed.setObjectName("grpLeftWheelSpeed")
        self.verticalLayout_lws = QtWidgets.QVBoxLayout(self.grpLeftWheelSpeed)
        self.verticalLayout_lws.setObjectName("verticalLayout_lws")
        self.lblLeftWheelSpeed = QtWidgets.QLabel(self.grpLeftWheelSpeed)
        self.lblLeftWheelSpeed.setStyleSheet("QLabel{}")
        self.lblLeftWheelSpeed.setObjectName("lblLeftWheelSpeed")
        self.verticalLayout_lws.addWidget(self.lblLeftWheelSpeed)
        self.lblLeftWheelSpeedSub = QtWidgets.QLabel(self.grpLeftWheelSpeed)
        self.lblLeftWheelSpeedSub.setStyleSheet("QLabel{color:#8ea2c8;}")
        self.lblLeftWheelSpeedSub.setObjectName("lblLeftWheelSpeedSub")
        self.verticalLayout_lws.addWidget(self.lblLeftWheelSpeedSub)
        self.horizontalLayout_over2.addWidget(self.grpLeftWheelSpeed)
        self.grpRightWheelSpeed = QtWidgets.QGroupBox(self.tabOverview)
        self.grpRightWheelSpeed.setObjectName("grpRightWheelSpeed")
        self.verticalLayout_rws = QtWidgets.QVBoxLayout(self.grpRightWheelSpeed)
        self.verticalLayout_rws.setObjectName("verticalLayout_rws")
        self.lblRightWheelSpeed = QtWidgets.QLabel(self.grpRightWheelSpeed)
        self.lblRightWheelSpeed.setStyleSheet("QLabel{}")
        self.lblRightWheelSpeed.setObjectName("lblRightWheelSpeed")
        self.verticalLayout_rws.addWidget(self.lblRightWheelSpeed)
        self.lblRightWheelSpeedSub = QtWidgets.QLabel(self.grpRightWheelSpeed)
        self.lblRightWheelSpeedSub.setStyleSheet("QLabel{color:#8ea2c8;}")
        self.lblRightWheelSpeedSub.setObjectName("lblRightWheelSpeedSub")
        self.verticalLayout_rws.addWidget(self.lblRightWheelSpeedSub)
        self.horizontalLayout_over2.addWidget(self.grpRightWheelSpeed)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_over2.addItem(spacerItem3)
        self.verticalLayout_overview.addLayout(self.horizontalLayout_over2)
        self.tabsMain.addTab(self.tabOverview, "")
        self.tabThermal = QtWidgets.QWidget()
        self.tabThermal.setObjectName("tabThermal")
        self.horizontalLayout_thermal = QtWidgets.QHBoxLayout(self.tabThermal)
        self.horizontalLayout_thermal.setContentsMargins(12, -1, 12, -1)
        self.horizontalLayout_thermal.setObjectName("horizontalLayout_thermal")
        self.verticalLayout_thermalLeft = QtWidgets.QVBoxLayout()
        self.verticalLayout_thermalLeft.setObjectName("verticalLayout_thermalLeft")
        self.grpLeftInverterMosfets = QtWidgets.QGroupBox(self.tabThermal)
        self.grpLeftInverterMosfets.setObjectName("grpLeftInverterMosfets")
        self.gridlayout = QtWidgets.QGridLayout(self.grpLeftInverterMosfets)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtWidgets.QLabel(self.grpLeftInverterMosfets)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.lblLeftMosfet1 = QtWidgets.QLabel(self.grpLeftInverterMosfets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLeftMosfet1.sizePolicy().hasHeightForWidth())
        self.lblLeftMosfet1.setSizePolicy(sizePolicy)
        self.lblLeftMosfet1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLeftMosfet1.setObjectName("lblLeftMosfet1")
        self.gridlayout.addWidget(self.lblLeftMosfet1, 0, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(self.grpLeftInverterMosfets)
        self.label1.setObjectName("label1")
        self.gridlayout.addWidget(self.label1, 1, 0, 1, 1)
        self.lblLeftMosfet2 = QtWidgets.QLabel(self.grpLeftInverterMosfets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLeftMosfet2.sizePolicy().hasHeightForWidth())
        self.lblLeftMosfet2.setSizePolicy(sizePolicy)
        self.lblLeftMosfet2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLeftMosfet2.setObjectName("lblLeftMosfet2")
        self.gridlayout.addWidget(self.lblLeftMosfet2, 1, 1, 1, 1)
        self.label2 = QtWidgets.QLabel(self.grpLeftInverterMosfets)
        self.label2.setObjectName("label2")
        self.gridlayout.addWidget(self.label2, 2, 0, 1, 1)
        self.lblLeftMosfet3 = QtWidgets.QLabel(self.grpLeftInverterMosfets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLeftMosfet3.sizePolicy().hasHeightForWidth())
        self.lblLeftMosfet3.setSizePolicy(sizePolicy)
        self.lblLeftMosfet3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLeftMosfet3.setObjectName("lblLeftMosfet3")
        self.gridlayout.addWidget(self.lblLeftMosfet3, 2, 1, 1, 1)
        self.verticalLayout_thermalLeft.addWidget(self.grpLeftInverterMosfets)
        self.grpRightInverterMosfets = QtWidgets.QGroupBox(self.tabThermal)
        self.grpRightInverterMosfets.setObjectName("grpRightInverterMosfets")
        self.gridlayout1 = QtWidgets.QGridLayout(self.grpRightInverterMosfets)
        self.gridlayout1.setObjectName("gridlayout1")
        self.label3 = QtWidgets.QLabel(self.grpRightInverterMosfets)
        self.label3.setObjectName("label3")
        self.gridlayout1.addWidget(self.label3, 0, 0, 1, 1)
        self.lblRightMosfet1 = QtWidgets.QLabel(self.grpRightInverterMosfets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRightMosfet1.sizePolicy().hasHeightForWidth())
        self.lblRightMosfet1.setSizePolicy(sizePolicy)
        self.lblRightMosfet1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRightMosfet1.setObjectName("lblRightMosfet1")
        self.gridlayout1.addWidget(self.lblRightMosfet1, 0, 1, 1, 1)
        self.label4 = QtWidgets.QLabel(self.grpRightInverterMosfets)
        self.label4.setObjectName("label4")
        self.gridlayout1.addWidget(self.label4, 1, 0, 1, 1)
        self.lblRightMosfet2 = QtWidgets.QLabel(self.grpRightInverterMosfets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRightMosfet2.sizePolicy().hasHeightForWidth())
        self.lblRightMosfet2.setSizePolicy(sizePolicy)
        self.lblRightMosfet2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRightMosfet2.setObjectName("lblRightMosfet2")
        self.gridlayout1.addWidget(self.lblRightMosfet2, 1, 1, 1, 1)
        self.label5 = QtWidgets.QLabel(self.grpRightInverterMosfets)
        self.label5.setObjectName("label5")
        self.gridlayout1.addWidget(self.label5, 2, 0, 1, 1)
        self.lblRightMosfet3 = QtWidgets.QLabel(self.grpRightInverterMosfets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRightMosfet3.sizePolicy().hasHeightForWidth())
        self.lblRightMosfet3.setSizePolicy(sizePolicy)
        self.lblRightMosfet3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRightMosfet3.setObjectName("lblRightMosfet3")
        self.gridlayout1.addWidget(self.lblRightMosfet3, 2, 1, 1, 1)
        self.verticalLayout_thermalLeft.addWidget(self.grpRightInverterMosfets)
        self.grpMotorTemps = QtWidgets.QGroupBox(self.tabThermal)
        self.grpMotorTemps.setObjectName("grpMotorTemps")
        self.gridlayout2 = QtWidgets.QGridLayout(self.grpMotorTemps)
        self.gridlayout2.setObjectName("gridlayout2")
        self.label6 = QtWidgets.QLabel(self.grpMotorTemps)
        self.label6.setObjectName("label6")
        self.gridlayout2.addWidget(self.label6, 0, 0, 1, 1)
        self.lblLeftMotorTemp = QtWidgets.QLabel(self.grpMotorTemps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLeftMotorTemp.sizePolicy().hasHeightForWidth())
        self.lblLeftMotorTemp.setSizePolicy(sizePolicy)
        self.lblLeftMotorTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLeftMotorTemp.setObjectName("lblLeftMotorTemp")
        self.gridlayout2.addWidget(self.lblLeftMotorTemp, 0, 1, 1, 1)
        self.label7 = QtWidgets.QLabel(self.grpMotorTemps)
        self.label7.setObjectName("label7")
        self.gridlayout2.addWidget(self.label7, 1, 0, 1, 1)
        self.lblRightMotorTemp = QtWidgets.QLabel(self.grpMotorTemps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRightMotorTemp.sizePolicy().hasHeightForWidth())
        self.lblRightMotorTemp.setSizePolicy(sizePolicy)
        self.lblRightMotorTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRightMotorTemp.setObjectName("lblRightMotorTemp")
        self.gridlayout2.addWidget(self.lblRightMotorTemp, 1, 1, 1, 1)
        self.verticalLayout_thermalLeft.addWidget(self.grpMotorTemps)
        self.horizontalLayout_thermal.addLayout(self.verticalLayout_thermalLeft)
        self.verticalLayout_thermalRight = QtWidgets.QVBoxLayout()
        self.verticalLayout_thermalRight.setObjectName("verticalLayout_thermalRight")
        self.grpThermalSummary = QtWidgets.QGroupBox(self.tabThermal)
        self.grpThermalSummary.setObjectName("grpThermalSummary")
        self.gridlayout3 = QtWidgets.QGridLayout(self.grpThermalSummary)
        self.gridlayout3.setObjectName("gridlayout3")
        self.label8 = QtWidgets.QLabel(self.grpThermalSummary)
        self.label8.setObjectName("label8")
        self.gridlayout3.addWidget(self.label8, 0, 0, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem4)
        self.lblSummaryLeftMos = QtWidgets.QLabel(self.grpThermalSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSummaryLeftMos.sizePolicy().hasHeightForWidth())
        self.lblSummaryLeftMos.setSizePolicy(sizePolicy)
        self.lblSummaryLeftMos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSummaryLeftMos.setObjectName("lblSummaryLeftMos")
        self.hboxlayout.addWidget(self.lblSummaryLeftMos)
        self.gridlayout3.addLayout(self.hboxlayout, 0, 1, 1, 1)
        self.label9 = QtWidgets.QLabel(self.grpThermalSummary)
        self.label9.setObjectName("label9")
        self.gridlayout3.addWidget(self.label9, 1, 0, 1, 1)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem5)
        self.lblSummaryRightMos = QtWidgets.QLabel(self.grpThermalSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSummaryRightMos.sizePolicy().hasHeightForWidth())
        self.lblSummaryRightMos.setSizePolicy(sizePolicy)
        self.lblSummaryRightMos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSummaryRightMos.setObjectName("lblSummaryRightMos")
        self.hboxlayout1.addWidget(self.lblSummaryRightMos)
        self.gridlayout3.addLayout(self.hboxlayout1, 1, 1, 1, 1)
        self.label10 = QtWidgets.QLabel(self.grpThermalSummary)
        self.label10.setObjectName("label10")
        self.gridlayout3.addWidget(self.label10, 2, 0, 1, 1)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem6)
        self.lblSummaryMotor = QtWidgets.QLabel(self.grpThermalSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSummaryMotor.sizePolicy().hasHeightForWidth())
        self.lblSummaryMotor.setSizePolicy(sizePolicy)
        self.lblSummaryMotor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSummaryMotor.setObjectName("lblSummaryMotor")
        self.hboxlayout2.addWidget(self.lblSummaryMotor)
        self.gridlayout3.addLayout(self.hboxlayout2, 2, 1, 1, 1)
        self.label11 = QtWidgets.QLabel(self.grpThermalSummary)
        self.label11.setObjectName("label11")
        self.gridlayout3.addWidget(self.label11, 3, 0, 1, 1)
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        spacerItem7 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem7)
        self.lblSummaryAmbient = QtWidgets.QLabel(self.grpThermalSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSummaryAmbient.sizePolicy().hasHeightForWidth())
        self.lblSummaryAmbient.setSizePolicy(sizePolicy)
        self.lblSummaryAmbient.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSummaryAmbient.setObjectName("lblSummaryAmbient")
        self.hboxlayout3.addWidget(self.lblSummaryAmbient)
        self.gridlayout3.addLayout(self.hboxlayout3, 3, 1, 1, 1)
        self.verticalLayout_thermalRight.addWidget(self.grpThermalSummary)
        self.horizontalLayout_thermal.addLayout(self.verticalLayout_thermalRight)
        self.tabsMain.addTab(self.tabThermal, "")
        self.tabElectrical = QtWidgets.QWidget()
        self.tabElectrical.setObjectName("tabElectrical")
        self.layoutElectricalRoot = QtWidgets.QHBoxLayout(self.tabElectrical)
        self.layoutElectricalRoot.setContentsMargins(12, -1, 12, -1)
        self.layoutElectricalRoot.setObjectName("layoutElectricalRoot")
        self.grpElectricalOverview = QtWidgets.QGroupBox(self.tabElectrical)
        self.grpElectricalOverview.setObjectName("grpElectricalOverview")
        self.gridElectrical = QtWidgets.QGridLayout(self.grpElectricalOverview)
        self.gridElectrical.setObjectName("gridElectrical")
        self.label12 = QtWidgets.QLabel(self.grpElectricalOverview)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label12.setFont(font)
        self.label12.setObjectName("label12")
        self.gridElectrical.addWidget(self.label12, 0, 0, 1, 1)
        self.lblElecVoltage = QtWidgets.QLabel(self.grpElectricalOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblElecVoltage.sizePolicy().hasHeightForWidth())
        self.lblElecVoltage.setSizePolicy(sizePolicy)
        self.lblElecVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblElecVoltage.setObjectName("lblElecVoltage")
        self.gridElectrical.addWidget(self.lblElecVoltage, 0, 1, 1, 1)
        self.label13 = QtWidgets.QLabel(self.grpElectricalOverview)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label13.setFont(font)
        self.label13.setObjectName("label13")
        self.gridElectrical.addWidget(self.label13, 1, 0, 1, 1)
        self.lblElecCurrent = QtWidgets.QLabel(self.grpElectricalOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblElecCurrent.sizePolicy().hasHeightForWidth())
        self.lblElecCurrent.setSizePolicy(sizePolicy)
        self.lblElecCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.lblElecCurrent.setObjectName("lblElecCurrent")
        self.gridElectrical.addWidget(self.lblElecCurrent, 1, 1, 1, 1)
        self.label14 = QtWidgets.QLabel(self.grpElectricalOverview)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label14.setFont(font)
        self.label14.setObjectName("label14")
        self.gridElectrical.addWidget(self.label14, 2, 0, 1, 1)
        self.lblElecPower = QtWidgets.QLabel(self.grpElectricalOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblElecPower.sizePolicy().hasHeightForWidth())
        self.lblElecPower.setSizePolicy(sizePolicy)
        self.lblElecPower.setAlignment(QtCore.Qt.AlignCenter)
        self.lblElecPower.setObjectName("lblElecPower")
        self.gridElectrical.addWidget(self.lblElecPower, 2, 1, 1, 1)
        self.label15 = QtWidgets.QLabel(self.grpElectricalOverview)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label15.setFont(font)
        self.label15.setObjectName("label15")
        self.gridElectrical.addWidget(self.label15, 3, 0, 1, 1)
        self.lblElecEnergy = QtWidgets.QLabel(self.grpElectricalOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblElecEnergy.sizePolicy().hasHeightForWidth())
        self.lblElecEnergy.setSizePolicy(sizePolicy)
        self.lblElecEnergy.setAlignment(QtCore.Qt.AlignCenter)
        self.lblElecEnergy.setObjectName("lblElecEnergy")
        self.gridElectrical.addWidget(self.lblElecEnergy, 3, 1, 1, 1)
        self.progressElecSOC = QtWidgets.QProgressBar(self.grpElectricalOverview)
        self.progressElecSOC.setProperty("value", 0)
        self.progressElecSOC.setObjectName("progressElecSOC")
        self.gridElectrical.addWidget(self.progressElecSOC, 4, 0, 1, 2)
        self.layoutElectricalRoot.addWidget(self.grpElectricalOverview)
        self.tabsMain.addTab(self.tabElectrical, "")
        self.verticalLayout_central.addWidget(self.tabsMain)
        self.verticalLayout_central.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabsMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ASURT"))
        self.titleLabel.setText(_translate("MainWindow", "ASURT"))
        self.hostedByLabel.setText(_translate("MainWindow", "HOSTED BY"))
        self.grpSession.setTitle(_translate("MainWindow", "SESSION"))
        self.cmbSession.setItemText(0, _translate("MainWindow", "Practice"))
        self.cmbSession.setItemText(1, _translate("MainWindow", "Qualifying"))
        self.cmbSession.setItemText(2, _translate("MainWindow", "Race"))
        self.grpLap.setTitle(_translate("MainWindow", "Lap"))
        self.grpSpeedTop.setTitle(_translate("MainWindow", "SPEED"))
        self.lblSpeedTop.setText(_translate("MainWindow", "0 km/h"))
        self.lblSpeedTop.setProperty("class", _translate("MainWindow", "measure"))
        self.grpBattery.setTitle(_translate("MainWindow", "BATTERY"))
        self.progressBattery.setFormat(_translate("MainWindow", "%p%"))
        self.progressBattery.setProperty("class", _translate("MainWindow", "measure"))
        self.grpTimeTop.setTitle(_translate("MainWindow", "TIME"))
        self.lblTimeTop.setText(_translate("MainWindow", "--:--:--"))
        self.lblTimeTop.setProperty("class", _translate("MainWindow", "measure"))
        self.grpAmbientTop.setTitle(_translate("MainWindow", "AMBIENT"))
        self.lblAmbientTop.setText(_translate("MainWindow", "0.0 °C"))
        self.lblAmbientTop.setProperty("class", _translate("MainWindow", "measure"))
        self.grpVehicleSpeed.setTitle(_translate("MainWindow", "VEHICLE SPEED"))
        self.lblSpeedValue.setText(_translate("MainWindow", "0"))
        self.lblSpeedValue.setProperty("class", _translate("MainWindow", "measure"))
        self.lblSpeedUnits.setText(_translate("MainWindow", "KM/H"))
        self.lblSpeedUnits.setProperty("class", _translate("MainWindow", "unit"))
        self.grpTrackMap.setTitle(_translate("MainWindow", "TRACK MAP"))
        self.labelGPS.setText(_translate("MainWindow", "GPS"))
        self.lblLat.setText(_translate("MainWindow", "Lat 0.0000, Lon 0.0000"))
        self.lblLat.setProperty("class", _translate("MainWindow", "measure"))
        self.labelHeading.setText(_translate("MainWindow", "HEADING"))
        self.lblHeading.setText(_translate("MainWindow", "000°"))
        self.lblHeading.setProperty("class", _translate("MainWindow", "measure"))
        self.lblHeadingDir.setText(_translate("MainWindow", "---"))
        self.grpPackVoltage.setTitle(_translate("MainWindow", "PACK VOLTAGE"))
        self.lblPackVoltage.setText(_translate("MainWindow", "0.0 V"))
        self.lblPackVoltage.setProperty("class", _translate("MainWindow", "measure"))
        self.lblPackVoltageSub.setText(_translate("MainWindow", "Instantaneous DC bus voltage"))
        self.grpInvTemp.setTitle(_translate("MainWindow", "INVERTER TEMP (Max MOSFET)"))
        self.lblInverterTemp.setText(_translate("MainWindow", "0.0 °C"))
        self.lblInverterTemp.setProperty("class", _translate("MainWindow", "measure"))
        self.lblInvTempSub.setText(_translate("MainWindow", "Max MOSFET case temperature"))
        self.grpLeftWheelSpeed.setTitle(_translate("MainWindow", "LEFT WHEEL SPEED"))
        self.lblLeftWheelSpeed.setText(_translate("MainWindow", "0.0 km/h"))
        self.lblLeftWheelSpeed.setProperty("class", _translate("MainWindow", "measure"))
        self.lblLeftWheelSpeedSub.setText(_translate("MainWindow", "Left wheel speed"))
        self.grpRightWheelSpeed.setTitle(_translate("MainWindow", "RIGHT WHEEL SPEED"))
        self.lblRightWheelSpeed.setText(_translate("MainWindow", "0.0 km/h"))
        self.lblRightWheelSpeed.setProperty("class", _translate("MainWindow", "measure"))
        self.lblRightWheelSpeedSub.setText(_translate("MainWindow", "Right wheel speed"))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.tabOverview), _translate("MainWindow", "Overview"))
        self.grpLeftInverterMosfets.setTitle(_translate("MainWindow", "LEFT INVERTER MOSFETS (°C)"))
        self.label.setText(_translate("MainWindow", "MOSFET 1"))
        self.lblLeftMosfet1.setText(_translate("MainWindow", "0.0 °C"))
        self.lblLeftMosfet1.setProperty("class", _translate("MainWindow", "measure"))
        self.label1.setText(_translate("MainWindow", "MOSFET 2"))
        self.lblLeftMosfet2.setText(_translate("MainWindow", "0.0 °C"))
        self.lblLeftMosfet2.setProperty("class", _translate("MainWindow", "measure"))
        self.label2.setText(_translate("MainWindow", "MOSFET 3"))
        self.lblLeftMosfet3.setText(_translate("MainWindow", "0.0 °C"))
        self.lblLeftMosfet3.setProperty("class", _translate("MainWindow", "measure"))
        self.grpRightInverterMosfets.setTitle(_translate("MainWindow", "RIGHT INVERTER MOSFETS (°C)"))
        self.label3.setText(_translate("MainWindow", "MOSFET 1"))
        self.lblRightMosfet1.setText(_translate("MainWindow", "0.0 °C"))
        self.lblRightMosfet1.setProperty("class", _translate("MainWindow", "measure"))
        self.label4.setText(_translate("MainWindow", "MOSFET 2"))
        self.lblRightMosfet2.setText(_translate("MainWindow", "0.0 °C"))
        self.lblRightMosfet2.setProperty("class", _translate("MainWindow", "measure"))
        self.label5.setText(_translate("MainWindow", "MOSFET 3"))
        self.lblRightMosfet3.setText(_translate("MainWindow", "0.0 °C"))
        self.lblRightMosfet3.setProperty("class", _translate("MainWindow", "measure"))
        self.grpMotorTemps.setTitle(_translate("MainWindow", "MOTOR TEMPERATURES (°C)"))
        self.label6.setText(_translate("MainWindow", "Left Motor Stator"))
        self.lblLeftMotorTemp.setText(_translate("MainWindow", "0.0 °C"))
        self.lblLeftMotorTemp.setProperty("class", _translate("MainWindow", "measure"))
        self.label7.setText(_translate("MainWindow", "Right Motor Stator"))
        self.lblRightMotorTemp.setText(_translate("MainWindow", "0.0 °C"))
        self.lblRightMotorTemp.setProperty("class", _translate("MainWindow", "measure"))
        self.grpThermalSummary.setTitle(_translate("MainWindow", "THERMAL SUMMARY"))
        self.label8.setText(_translate("MainWindow", "Left Inverter MOSFET"))
        self.label8.setProperty("class", _translate("MainWindow", "summaryText"))
        self.lblSummaryLeftMos.setText(_translate("MainWindow", "0.0 °C"))
        self.lblSummaryLeftMos.setProperty("class", _translate("MainWindow", "measure summaryValue"))
        self.label9.setText(_translate("MainWindow", "Right Inverter MOSFET"))
        self.label9.setProperty("class", _translate("MainWindow", "summaryText"))
        self.lblSummaryRightMos.setText(_translate("MainWindow", "0.0 °C"))
        self.lblSummaryRightMos.setProperty("class", _translate("MainWindow", "measure summaryValue"))
        self.label10.setText(_translate("MainWindow", "Motor Stator"))
        self.label10.setProperty("class", _translate("MainWindow", "summaryText"))
        self.lblSummaryMotor.setText(_translate("MainWindow", "0.0 °C"))
        self.lblSummaryMotor.setProperty("class", _translate("MainWindow", "measure summaryValue"))
        self.label11.setText(_translate("MainWindow", "Ambient"))
        self.label11.setProperty("class", _translate("MainWindow", "summaryText"))
        self.lblSummaryAmbient.setText(_translate("MainWindow", "0.0 °C"))
        self.lblSummaryAmbient.setProperty("class", _translate("MainWindow", "measure summaryValue"))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.tabThermal), _translate("MainWindow", "Thermal"))
        self.grpElectricalOverview.setTitle(_translate("MainWindow", "ELECTRICAL OVERVIEW"))
        self.grpElectricalOverview.setProperty("class", _translate("MainWindow", "elecCard"))
        self.label12.setText(_translate("MainWindow", "Pack Voltage"))
        self.label12.setProperty("class", _translate("MainWindow", "electricalLabel"))
        self.lblElecVoltage.setText(_translate("MainWindow", "0.0 V"))
        self.lblElecVoltage.setProperty("class", _translate("MainWindow", "electricalValue"))
        self.label13.setText(_translate("MainWindow", "Pack Current"))
        self.label13.setProperty("class", _translate("MainWindow", "electricalLabel"))
        self.lblElecCurrent.setText(_translate("MainWindow", "0.0 A"))
        self.lblElecCurrent.setProperty("class", _translate("MainWindow", "electricalValue"))
        self.label14.setText(_translate("MainWindow", "Power"))
        self.label14.setProperty("class", _translate("MainWindow", "electricalLabel"))
        self.lblElecPower.setText(_translate("MainWindow", "0.0 W"))
        self.lblElecPower.setProperty("class", _translate("MainWindow", "electricalValue"))
        self.label15.setText(_translate("MainWindow", "Energy Consumed"))
        self.label15.setProperty("class", _translate("MainWindow", "electricalLabel"))
        self.lblElecEnergy.setText(_translate("MainWindow", "0.0 Wh"))
        self.lblElecEnergy.setProperty("class", _translate("MainWindow", "electricalValue"))
        self.progressElecSOC.setFormat(_translate("MainWindow", "SOC %p%"))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.tabElectrical), _translate("MainWindow", "Electrical"))
